version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOSTNAME: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678@Abc
      POSTGRES_DB: trading_system
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
#      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./trading_system:/var/lib/postgresql/data/