USERNAME_LEN_MIN = 4
USERNAME_LEN_MAX = 25
USERNAME_TIP = "Don't worry. you can change it later."

REALNAME_LEN_MIN = 4
REALNAME_LEN_MAX = 25

PASSWORD_LEN_MIN = 6
PASSWORD_LEN_MAX = 16

PIN_BAR_BODY_RATIO = 0.003
PIN_BAR_CANDLE_LENGTH_AND_BODY_RATIO = 1/3

DOJI_OPEN_CLOSE_DIFF_RATIO = 0.001
DOJI_CANDLE_LENGTH_AND_BODY_RATIO = 3

DEFAULT_SCHEMA = 'public'